# Set the base image to Ubuntu
#FROM ubuntu
FROM ubuntu:16.04
# File Author / Maintainer
MAINTAINER Adrian Alves <aalves@gmail.com>

# Update the sources list
RUN apt-get update

# Install basic applications
RUN apt-get install -y tar git curl nano wget dialog net-tools build-essential 

# Install Python and Basic Python Tools
RUN apt-get install -y python3 python3-flask-restful python3-flask python3-redis python3-xmltodict python3-requests python3-flask-restful python3-simplejson python3-setuptools

# Copy the applixcation folder inside the container
COPY cat-history.py /python-app
ADD cat-history.py /python-app

# Set the default directory for our environment
ENV HOME /python-app
WORKDIR /python-app

# Expose python app port 5000
EXPOSE 5000

#run app
ENTRYPOINT ["python"]
CMD ["cat-history.py.py"]
